# Part 1 of my HOTS hero select program! Here I will try work on the hero filter

qualities = {
      'ambusher' : ['Dehaka','Greymane','Illidan','Nova','Raynor','Sonya','Zeratul','Diablo','Butcher'],
    	'aoeburst' : ['Azmodan','Chromie','Gazlowe','Guldan','Jaina','Kaelthas','LiMing','Murky'],
    	'blind' : ['Artanis','Johanna','LiLi','Auriel!'],
    	'bruiser' : ['Alarak','Anubarak','Artanis','Arthas','Dehaka','Leoric','Sonya','Tyrael','Zarya'],
    	'buffer' : ['Abathur','Brightwing','Chen','ETC','Kharazim','LiLi','Malfurion','Medivh','Morales','Rehgar','Tassadar','Tyrael','Uther','Tyrande','Raynor'],
    	'burstdamage' : ['Alarak','Azmodan','Butcher','Chromie','Gazlowe','Greymane','Guldan','Jaina','Kaelthas','LiMing','Murky','Nova','Zeratul'],
    	'crowdcontrol' : ['Alarak','Anubarak','Artanis','Arthas','Brightwing','Butcher','Dehaka','Diablo','ETC','Gazlowe','Jaina','Johanna','Kerrigan','Leoric','LiLi','Malfurion','Medivh','Morales','Muradin','Murky','Nova','Raynor','Rehgar','Rexxar','Sonya','Stiches','Sylvanas','Tassadar','Thrall','Tychus','Tyrael','Tyrande','Uther','Valla','Xul','Zagara','Zarya','Zeratul'],
    	'displacement' : ['Artanis','Diablo','ETC','Falstad','Gazlowe','Johanna','Kerrigan','Morales','Raynor','Stiches','Sylvanas','Tassadar','Tychus','Zarya','Alarak','Hammer','Tyrael','Auriel'],
    	'diver' : ['Anubarak','Artanis','Butcher','Chen','Diablo','ETC','Illidan','Kerrigan','Tyrael'],
    	'engage' : ['Diablo','Tyrael','Anubarak','Johanna','Zarya','Falstad','Zeratul','Arthas','Gazlowe','Sonya','Zagara','Leoric','Butcher'],
    	'fastrespawn' : ['Leoric','Murky','Diablo'],
    	'giantkiller' : ['Artanis','Arthas','Falstad','Hammer','Lunara','Raynor','Thrall','Tychus','Zeratul','Leoric','Valla'],
    	'globalatack' : ['Artanis','Azmodan','Falstad','Hammer','Illidan','Nova'],
    	'globalpresence' : ['Abathur','Brightwing','Dehaka','ETC','Falstad','Illidan','Zagara','Morales','Auriel'],
    	'healer' : ['Auriel','Brightwing','ETC','Kharazim','LiLi','Malfurion','Morales','Rehgar','Tyrande','Uther'],
    	'interrupter' : ['Alarak','Anubarak','Artanis','Auriel','Brightwing','Butcher','Dehaka','Diablo','ETC','Gazlowe','Illidan','Johanna','Kerrigan','Medivh','Morales','Muradin','Murky','Rexxar','Sonya','Stiches','Sylvanas','Tassadar','Thrall','Tychus','Tyrande','Uther','Zagara','Zarya','Zeratul'],
    	'invulnerable ' : ['Murky','Tyrael','Uther','Alarak'],
    	'longerrange' : ['Hammer','Raynor','Zagara'],
    	'mage' : ['Chromie','Guldan','Jaina','Kaelthas','LiMing'],
    	'melee' : ['Abathur','Alarak','Anubarak','Artanis','Arthas','Butcher','Chen','Dehaka','Diablo','ETC','Gazlowe','Greymane','Illidan','Johanna','Kerrigan','Kharazim','Leoric','Murky','Rehgar','Rexxar','Sonya','Stiches','Thrall','Tyrael','Xul','Zeratul'],
    	'mobility' : ['Anubarak','Artanis','Butcher','Chen','Diablo','Falstad','Tracer','Valla'],
    	'multiheal' : ['Auriel','Brightwing','ETC','Kharazim','Malfurion','Rehgar','Uther','LiLi'],
    	'pet' : ['Abathur','Jaina','Kerrigan','Nazeebo','Rexxar'],
    	'poison' : ['Guldan','Kaelthas','Lunara','Murky','Nazeebo','Sylvanas','Xul'],
    	'poke' : ['Azmodan','Brightwing','Chromie','Falstad','Guldan','Hammer','Jaina','Kaelthas','Kerrigan','LiLi','LiMing','Malfurion','Medivh','Morales','Murky','Nazeebo','Nova','Raynor','Rexxar','Sylvanas','Tassadar','Tyrael','Tyrande','Uther','Valla','Xul','Zagara','Zarya'],
    	'ranged' : ['Auriel','Azmodan','Brightwing','Chromie','Falstad','Guldan','Hammer','Jaina','Kaelthas','LiLi','LiMing','Lunara','Malfurion','Medivh','Morales','Muradin','Nazeebo','Nova','Raynor','Rexxar','Sylvanas','Tassadar','Tracer','Tychus','Tyrande','Uther','Valla','Zagara','Zarya'],
    	'reveal' : ['Kharazim','Lunara','Medivh','Rehgar','Rexxar','Tassadar'],
    	'root' : ['Malfurion','Thrall','Xul'],
    	'selfsustain' : ['Artanis','Arthas','Chen','Dehaka','Guldan','Hammer','Leoric','Muradin','Thrall','Tychus','Stiches','ETC','Illidan','Butcher'],
    	'shields' : ['Abathur','Anubarak','Artanis','Brightwing','Chen','Jaina','Johanna','Medivh','Morales','Tassadar','Tychus','Tyrande','Xul','Zarya'],
    	'siege' : ['Abathur','Anubarak','Arthas','Azmodan','Gazlowe','Hammer','LiMing','Murky','Nazeebo','Sylvanas','Xul','Zagara'],
    	'silence' : ['Alarak','Malfurion','Sylvanas','Butcher'],
    	'singleheal' : ['Abathur','LiLi','Malfurion','Morales','Tassadar','Tyrande','Uther'],
    	'slow' : ['Arthas','Brightwing','Butcher','Falstad','Gazlowe','Jaina','Leoric','Muradin','Murky','Nova','Rehgar','Stiches','Tyrael','Xul','Zagara','Zeratul'],
    	'splitpush' : ['Abathur','Azmodan','Falstad','Gazlowe','Murky','Sylvanas','Xul','Zagara'],
    	'stasis' : ['Medivh','Stiches','Zagara','Zeratul','Auriel'],
    	'stealth' : ['Brightwing','Greymane','Hammer','Nova','Tyrande','Zeratul'],
    	'stun' : ['Dehaka','ETC','Johanna','Kerrigan','Muradin','Murky','Rexxar','Sonya','Thrall','Tyrande','Uther','Valla','Anubarak','Gazlowe','Butcher'],
    	'sustaindamage' : ['Butcher','Falstad','Greymane','Guldan','Hammer','Illidan','Kerrigan','Kharazim','Lunara','Nazeebo','Raynor','Sonya','Valla','Zagara'],
    	'tank' : ['Arthas','Chen','Diablo','ETC','Johanna','Leoric','Muradin','Stiches','Tyrael','Zarya'],
    	'waveclear' : ['Arthas','Auriel','Azmodan','Chromie','Dehaka','Gazlowe','Guldan','Jaina','Johanna','Kaelthas','Kerrigan','Leoric','LiMing','Murky','Rexxar','Sylvanas','Tassadar','Tychus','Valla','Xul','Zagara','Zeratul'],
    	'masterlist' : ['Abathur','Alarak','Anubarak','Artanis','Arthas','Auriel','Azmodan','Brightwing','Butcher','Chen','Chromie','Dehaka','Diablo','ETC','Falstad','Gazlowe','Greymane','Guldan','Hammer','Illidan','Jaina','Johanna','Kaelthas','Kerrigan','Kharazim','Leoric','LiLi','LiMing','Lunara','Malfurion','Medivh','Morales','Muradin','Murky','Nazeebo','Nova','Raynor','Rehgar','Rexxar','Sonya','Stiches','Sylvanas','Tassadar','Thrall','Tracer','Tychus','Tyrael','Tyrande','Uther','Valla','Xul','Zagara','Zarya','Zeratul']
    }

print ("no bugs so far")
